### ISSUE TITLE
Why do i need to close socket before trying to connect again?

### ISSUE THREAD

**Issue by printfKrzysztof** [stm32duino/LwIP#7]
Hello,
Recently i have been working with lwip to connect one device to available server. Idea was simple using: lwip_connect() i was trying to connect to server. If i got no error it was okay, but if i received RTE_ERR i lwip_connect() different ip. After some time i realized that i need to close socket before doing this. Why does it work this way? Instead of just connecting socket is useless unless you want to connect to the same ip. Also i have a question about the easiest way to handle routing that consists of 2 gsm sockets and 2 ethernet sockets. Thanks in advance.
Rgrds

**Comment by fpistm** [comment]
Hi,
This library is only a porting of the https://github.com/STMicroelectronics/stm32_mw_lwip to fit Arduino library specification in order to be used by https://github.com/stm32duino/STM32Ethernet.
As stated here https://github.com/STMicroelectronics/stm32_mw_lwip#troubleshooting
You should submit a topic on [ST Community](https://community.st.com/s/)
